-- AlterTable
ALTER TABLE "MockInvestor" ALTER COLUMN "investAmount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Startup" ALTER COLUMN "simInvest" SET DATA TYPE BIGINT,
ALTER COLUMN "revenue" SET DATA TYPE BIGINT;
