###
GET http://localhost:3000/api/comparisons/?limit=20

###
GET http://localhost:3000/api/comparisons/recent-selection

###
GET http://localhost:3000/api/comparisons/compare-result?orderBy=asc&sortBy=revenue

